In [1]:
import numpy as np
import math
import random as rand

In [45]:
'''
Algoritma PSO pada program ini hanya menerima optimisasi fungsi objektif satu variabel.
Stopping condition berdasarkan jumlah iterasi.
Mekanisme Status Updating berdasarkan Kennedy-Eberhart (1995)
'''

class Swarm:
    def __init__(self, obj_func, pop, rho=1, c=[1,1], r=[rand.random(), rand.random()], it=15):
        self.c = c
        self.r = r
        self.rho = rho
        self.it = it
        
        self.n_pop = pop.shape[0]
        self.pop = np.zeros((self.n_pop, it+1))
        self.pop[:, 0] = pop.copy()
        
        self.func = obj_func
        self.fitness = np.zeros((self.n_pop, self.it+1))
        
        self.xg = 0
        self.xl = np.zeros((self.n_pop, 1))
        self.v = np.zeros((self.n_pop, self.it+1))
    
    def adjust(self, param, t):
        if t == 0:
            return np.zeros((self.n_pop, 1))
        elif t > 0:
            cognitive = self.c[0]*self.r[0]*(self.xl - self.pop[:, t-1])
            social = self.c[1]*self.r[1]*self.xg
            return self.rho + self.v[:, t-1] + cognitive + social
    
    def run(self):
        for it in range(0, self.it+1):
            self.v[:, it] = self.adjust(self.pop, it)[:, 0]
            if it > 0:
                self.pop[:, it] = self.pop[:, it-1] + self.v[:, it] # update populasi
            self.fitness[:, it] = self.func(self.pop[:, it])
            
            opt_grow = np.argmin(self.fitness[:, it])
            self.xg = self.pop[opt_grow, it]
            if it == 0:
                self.xl[:, 0] = self.pop[:, it]
            elif it > 0:
                for i in range(0, self.n_pop):
                    opt_lrow = np.argmin(self.fitness[i, 0:it+1])
                    self.xl[i, 0] = self.pop[i, opt_lrow]
            print("Populasi iterasi "+str(it)+"\n", self.pop)

In [46]:
x = np.array([-4,-3,2,5])

# cara mendefinisikan fungsi sbg. lambda -> lambda _var : f(_var)
f = lambda a : 2*a**2 + 4*a + 5
latihan = Swarm(f, x, it=5)
latihan.run()

Populasi iterasi 0
 [[-4.  0.  0.  0.  0.  0.]
 [-3.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]]
Populasi iterasi 1
 [[-4.         -4.96524681  0.          0.          0.          0.        ]
 [-3.         -3.25344016  0.          0.          0.          0.        ]
 [ 2.          5.30559307  0.          0.          0.          0.        ]
 [ 5.         10.44101302  0.          0.          0.          0.        ]]
Populasi iterasi 2
 [[-4.         -4.96524681 -6.3746955   0.          0.          0.        ]
 [-3.         -3.25344016 -3.9510822   0.          0.          0.        ]
 [ 2.          5.30559307  8.16698427  0.          0.          0.        ]
 [ 5.         10.44101302 15.43782416  0.          0.          0.        ]]
Populasi iterasi 3
 [[-4.         -4.96524681 -6.3746955  -7.68210404  0.          0.        ]
 [-3.         -3.25344016 -3.9510822  -4.5466841   0.          0.        ]
 [ 2.          5.30559307  8.16698427 11.13041561  0.      

In [47]:
latihan.fitness

array([[  21.        ,   34.44636456,   60.77470337,   92.30102885,
         110.95736452,   97.26826868],
       [  11.        ,   13.15598515,   20.41777233,   28.1579362 ,
          27.49708818,   13.63893558],
       [  21.        ,   82.521008  ,  171.06720132,  297.29396588,
         498.26485254,  842.57931368],
       [  75.        ,  264.79355764,  543.40412608,  930.65677803,
        1491.180828  , 2337.61317539]])

In [48]:
latihan.xl

array([[-4.],
       [-3.],
       [ 2.],
       [ 5.]])